export const MOCK_CATEGORIES = [
  "Tümü",
  "Ekonomi Sedan",
  "Orta Sedan",
  "Lüks Sedan",
];

export const MOCK_VEHICLES = [
  {
    id: 1,
    title: "Fiat Egea",
    category: "Ekonomi Sedan",
    price: 2500,
    transmission: "Manuel",
    fuel: "Benzin/Dizel",
    seats: 5,
    luggage: "440 LT",
    image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800",
    description: "Fiat Egea ekonomik yakıt tüketimi ve geniş iç hacmi ile günlük kullanımlar için ideal bir sedan araçtır. Hem şehir içi pratikliği hem de uzun yolda sunduğu konfor ile öne çıkar.",
    services: ["Çocuk Koltuğu", "Ek Sürücü", "Mini Hasar Güvencesi"],
  },
  {
    id: 2,
    title: "Renault Megane",
    category: "Orta Sedan",
    price: 3500,
    transmission: "Otomatik",
    fuel: "Dizel",
    seats: 5,
    luggage: "500 LT",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800",
    description: "Konforlu süspansiyon yapısı ve verimli motoru ile hem şehir içinde hem otoyolda konforlu bir sürüş performansı vadediyor.",
    services: ["Çocuk Koltuğu", "Ek Sürücü", "Navigasyon", "Mini Hasar Güvencesi"],
  },
  {
    id: 3,
    title: "Premium Model",
    category: "Lüks Sedan",
    price: 6500,
    transmission: "Otomatik",
    fuel: "Benzin",
    seats: 5,
    luggage: "480 LT",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    description: "Üst düzey malzeme kalitesi, gelişmiş güvenlik sistemleri ve güçlü motor performansı ile premium bir sürüş deneyimi yaşayın.",
    services: ["VIP Destek", "Tam Kasko", "Ek Sürücü"],
  },
  {
    id: 4,
    title: "Toyota Corolla",
    category: "Orta Sedan",
    price: 3200,
    transmission: "Otomatik",
    fuel: "Benzin",
    seats: 5,
    luggage: "470 LT",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800",
    description: "Konfor ve güvenliği bir araya getiren popüler orta sınıf sedan. Aile tatilleri için oldukça ideal.",
    services: ["Ek Sürücü", "Mini Hasar Güvencesi", "Lastik Güvencesi"],
  },
  {
    id: 5,
    title: "Audi A6",
    category: "Lüks Sedan",
    price: 6800,
    transmission: "Otomatik",
    fuel: "Dizel",
    seats: 5,
    luggage: "530 LT",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    description: "Geniş iç mekân ve sessiz kabin deneyimiyle iş seyahatlerinde her zaman beklentilerin üzerinde bir konfor.",
    services: ["VIP Destek", "Tam Kasko", "Sınırsız Kilometre"],
  }
];
